Footer
acm-uic/marketplace pull request #33
Opened 2023-10-04 01:38 UTC by floatsinkfc

Added 
- footer 
- scroll animation when user click shop now
- added a temporary product list to show footers
- changed all the link to open a new tab instead of changing tab from original
- make the footer color and button text color interact with light/dark mode button

2023-10-04 21:52 UTC, Ajknight121 requested changes

2023-10-04 21:52 UTC, Ajknight121 commented on app/components/header.jsx
> +                <Link className="text-2xl text-white hover:underline w" href='/Contributors'>Contact</Link>
This link should still be to the ACM contact page as it was before. The website contributor link will be in the footer.

2023-10-04 21:52 UTC, Ajknight121 commented on app/components/footer.jsx
Also add the ACM Linkedin (https://www.linkedin.com/company/acm-cs-uic/) and Instagram (https://www.instagram.com/acmatuic/)

2023-10-04 21:54 UTC, Ajknight121 commented
Awesome work! The scroll transition looks good and the colors are correct. This pull should also complete the hero pull request.

2023-10-04 22:10 UTC, Ajknight121 commented on app/components/footer.jsx
Add link called "Website Credit & Contributors" to the footer that navigates to the "/Contributors" page. I've added an example to the Figma

2023-10-05 06:25 UTC, floatsinkfc commented
since i did the navigates to the "/Contributors" page, I decided to change the contributor page a bit to fit the Figma design. 

I added
- header to contributor page with inverted color from original
- footer to contributor page 
- a title to contributor page
- when user click on github @ on contributor, it goes to new tab instead of opening it directly on the tab

but there is something that I could not figure out what to do is the 
- syncing light/dark mode from the shop page to contributor page

2023-10-06 03:45 UTC, Ajknight121 requested changes
The Header and Footer should actually be removed from all pages and added layout.jsx. Components added to layout.jsx should render on all other pages. Moving Header and footer to layout.jsx should solve the issues of keeping the same theme applied. This also could have been solved with React's useContext. I'll go over context in the next meeting.

2023-10-06 03:45 UTC, Ajknight121 commented on app/Contributors/page.jsx
> +"use client"
Remove state and header/footer

2023-10-06 03:45 UTC, Ajknight121 commented on app/page.jsx
Remove Header and Footer from this page.

2023-10-06 03:45 UTC, Ajknight121 commented on app/page.jsx
> +import { useEffect, useState, useRef } from "react";
remove useEffect

2023-10-06 05:03 UTC, floatsinkfc commented on app/page.jsx
Can I leave the header/footer in the main page for easy navigation and that could be removed once the layout.jsx was implemented? Everything else is resolved on the new commit

2023-10-06 19:12 UTC, Ajknight121 approved these changes
Spectacular work!

2023-10-06 19:13 UTC, merged