Header and Footer Layout
acm-uic/marketplace pull request #40
Opened 2023-10-07 23:31 UTC by floatsinkfc

I tried my best to implement the footer and header layout as a "theme" in react. It works perfectly fine for me syncing with all other pages along with inverting the header when user are on the "contributor" page.

2023-10-08 03:00 UTC, floatsinkfc commented
Updated 
- Changed the layout of contributor page instead of inverting header
- Added hero to the contributor page
- Revamp the contributor box, still kept the border color that user picked before
- Dark mode is synced among different pages 
- Added 1 new animation (typewriter)

2023-10-09 21:28 UTC, Ajknight121 requested changes
Incredible work, I like that you created the useTheme function. I also really like the animation and use of svgs, just center the social media links for the contributor page and this can be pulled. If you can get the cursor to disappear at the end of the animation it could be applied to the homepage in a separate pull.

2023-10-09 21:28 UTC, Ajknight121 commented on app/Contributors/contributorhero.jsx
> +      <div className="items-center flex flex-row bg-transparent w-full">
Center the social media links

2023-10-10 01:10 UTC, floatsinkfc commented
the social media should be centered and the cursor should now disappear after onAnimationEnd={}

2023-10-10 01:41 UTC, Ajknight121 approved these changes

2023-10-10 01:42 UTC, merged